---
# ============================================================================
# 🔧 CONEXÃO DE SORTE - ZOOKEEPER INFRAESTRUTURA
# ============================================================================
# Data de Criação: 17/09/2025 às 04:25 BRT
# Última Atualização: 17/09/2025 às 04:25 BRT
# Responsável: Sistema Automatizado
# Versão: 1.0.0
# ============================================================================
#
# ZOOKEEPER STANDALONE - Kafka Coordination Service
# - Docker Swarm deployment
# - Overlay encrypted network para segurança
# - Named volumes com placement constraints
# - Health checks otimizados para produção
# - Configuração específica para Kafka
# ============================================================================

services:
  # ============================================================================
  # 🔧 ZOOKEEPER - Kafka Coordination
  # ============================================================================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    hostname: conexao-zookeeper
    user: "1000:1000"
    init: true
    stop_grace_period: 45s
    environment:
      # 🔧 CONFIGURAÇÃO STANDALONE CORRIGIDA
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_MAX_CLIENT_CNXNS: 60
      ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT: 3
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: 24
      # 🛡️ CONFIGURAÇÃO STANDALONE EXPLÍCITA
      ZOOKEEPER_SERVERS: server.1=conexao-zookeeper:2888:3888
      # 🚀 PERFORMANCE E STABILIDADE
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms256m"
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: WARN
    networks:
      conexao-network-swarm:
        aliases:
          - conexao-zookeeper
          - zookeeper
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_logs:/var/lib/zookeeper/log
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      # 🩺 HEALTH CHECK SEM DEPENDÊNCIAS EXTERNAS
      test: [
        "CMD-SHELL",
        "zkServer.sh status >/dev/null 2>&1 || ps aux | grep -q '[q]uorumPeerMain'"
      ]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s
    deploy:
      # 🛡️ SINGLE INSTANCE FORTE - PREVINE MÚLTIPLAS INSTÂNCIAS
      replicas: 1
      placement:
        constraints:
          - node.role == manager
        max_replicas_per_node: 1
      restart_policy:
        # 🔧 RESTART POLICY CONSERVADORA - EVITA LOOPS
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 600s
      resources:
        limits:
          # 🚀 RESOURCES ADEQUADOS PARA ZOOKEEPER
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 60s
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 30s
        failure_action: pause
        monitor: 60s

# ============================================================================
# 📦 VOLUMES EXTERNOS
# ============================================================================
volumes:
  zookeeper_data:
    external: true
    name: zookeeper_data
  zookeeper_logs:
    external: true
    name: zookeeper_logs

# ============================================================================
# 🌐 NETWORKS EXTERNOS
# ============================================================================
networks:
  conexao-network-swarm:
    external: true
    name: conexao-network-swarm
